parameters:
#    event.example.class: Yoda\EventBundle\Example

services:
#    event.example:
#        class: %event.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     event_report_manager:
         class: Yoda\EventBundle\Reporting\EventReportManager
         arguments: ["@doctrine.orm.entity_manager", "@router"]