<?php

namespace Yoda\EventBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository
{
    /**
     * @return Event[]
     */
    public function getAllEvents()
    {
        var_dump('hello');


//        return $this->createQueryBuilder('e')
//            ->andWhere('e.createdAt > :since')
//            ->setParameter('since', new \DateTime('24 Hours Ago'))
//            ->getQuery()
//            ->execute();
    }
}
